# CSV audit config for project 013
    input_glob: "data/013/input/*.csv"
    sample_rows: 5
    required_columns: ["id", "date", "amount"]
    numeric_columns: ["amount"]
    date_columns: ["date"]
    fail_on_missing_required: true
    log_dir: "logs/013"
    report_dir: "reports/013"
    results_dir: "results/013"
