[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dsq5-data-wrangling"
version = "0.0.1"
description = "Quarter 5 – Data Wrangling (self-contained utilities)"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
