input_glob: projects/013_dataset_audit_tool/data/013/input/*.csv
results_dir: results/013
report_dir: reports/013
log_dir: logs/013

required_columns:
  - date
  - category
  - amount

numeric_columns:
  - amount

fail_on_missing_required: true
